# Generated by Django 4.1.3 on 2023-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
