# Generated by Django 4.1.3 on 2023-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineAdmin', '0002_alter_mod_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='desc',
            field=models.TextField(max_length=1024),
        ),
    ]
